# render.yaml  (only the service stanza shown)
services:
  - type: web
    name: trading-bot-bingx
    runtime: docker          # ← change from “python”
    dockerfilePath: ./Dockerfile
    plan: free
    rootDir: .
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: TRADING_MODE
        value: demo
      - key: BINGX_API_KEY
        sync: false
      - key: BINGX_SECRET_KEY
        sync: false
      - key: LOG_LEVEL
        value: INFO
