services:
  - type: web
    name: trading-bot-bingx
    env: python
    buildCommand: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && source $HOME/.cargo/env && pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    plan: free
    envVars:
      - key: TRADING_MODE
        value: demo
      - key: BINGX_API_KEY
        sync: false
      - key: BINGX_SECRET_KEY
        sync: false
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHONPATH
        value: /opt/render/project/src
    healthCheckPath: /health
    autoDeploy: true
    rootDir: .
    buildFilter:
      paths:
      - "**"
      ignoredPaths:
      - "tests/**"
      - "*.md"
      - ".git/**"