# render.yaml for Python web service
services:
  - type: web
    name: trading-bot-bingx
    runtime: python
    buildCommand: pip install -r requirements-render.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    plan: free
    rootDir: .
    autoDeploy: true
    envVars:
      - key: TRADING_MODE
        value: demo
      - key: BINGX_API_KEY
        sync: false
      - key: BINGX_SECRET_KEY
        sync: false
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: 1
      - key: PYTHONUNBUFFERED
        value: 1
